from typing import Protocol
from .contracts import AthletePage, AthleteSnapshot

class AthleteRepository(Protocol):
    def get(self, identifier: str, actor_id: str) -> AthleteSnapshot | None: ...
    def list_for_owner(self, actor_id: str, cursor: str | None = None, limit: int = 50) -> AthletePage: ...
