from typing import Protocol
from .contracts import MatchPage, MatchSnapshot

class MatchRepository(Protocol):
    def get(self, identifier: str, actor_id: str) -> MatchSnapshot | None: ...
    def list_for_owner(self, actor_id: str, cursor: str | None = None, limit: int = 50) -> MatchPage: ...
